### ISSUE TITLE
Issue with EDuke32

### ISSUE THREAD

**Issue by Matthaiks** [KaleidonKep99/OmniMIDI#130]
**Problem**
Music won't play (apart from the main menu) in EDuke32 with OmniMIDI - Version 6.0.57, CR23 or newer. Older versions of OmniMIDI are fine.

**Steps to reproduce**
1. Run Duke Nukem 3D in EDuke32
2. Load any map

**Expected behavior**
Music should be playing.

**Environment**
Windows 10 v1809 x64

**Comment by KaleidonKep99** [comment]
It seems to play just fine for me, outside of the main menu as well.
![image](https://user-images.githubusercontent.com/11065274/50044662-1be3a700-0087-11e9-88ac-74455b8046a5.png)

Since EDuke32 doesn't seem to allow users to change the default MIDI out device, try patching it with the **"Windows Multimedia Wrapper"** tool in the configurator.

**Comment by Matthaiks** [comment]
Still nothing.
![omnimidi debug window v6 0 58 5](https://user-images.githubusercontent.com/3577122/50044754-a4167c00-0088-11e9-91bd-59be996737d0.png)!!

**Comment by Matthaiks** [comment]
Old EDuke32 version (20101230-1749). startup errors:
![duk1](https://user-images.githubusercontent.com/3577122/50044836-f1471d80-0089-11e9-992a-71dfcdb6a4fc.png)
![duk2](https://user-images.githubusercontent.com/3577122/50044841-f4420e00-0089-11e9-8f7d-11d7f4a828e5.png)

**Comment by KaleidonKep99** [comment]
> Old EDuke32 version (20101230-1749). startup errors:
> ![duk1](https://user-images.githubusercontent.com/3577122/50044836-f1471d80-0089-11e9-992a-71dfcdb6a4fc.png)
> ![duk2](https://user-images.githubusercontent.com/3577122/50044841-f4420e00-0089-11e9-8f7d-11d7f4a828e5.png)

Now that I think about it...
If older versions of EDuke behave like this, then it's probably something wrong in their code.

I'll add a checkbox in OmniMIDI, to allow users to disable the CookedPlayer caps.

**Comment by KaleidonKep99** [comment]
I've tried doing more debugging, and we've forgot to add a DriverCallback to MODM_STOP, which now works fine.
But still, EDuke32 now softlocks instead of giving no audio. I have no idea how and why.

Could you please report this issue to the developers? I can't register to the forum.

EDIT 1: GZDoom is not affected by this issue. It seems to work fine.

**Comment by KaleidonKep99** [comment]
Forget it! Fixed in 6.0.58.8.
Blame Microsoft's poor documentation...

Remember to repatch EDuke32 with the updated Windows Multimedia Wrapper in the latest update.
