### ISSUE TITLE
"Buffers are still in the queue." error when closing wmplayer after playing midi, and MAMPlayer refuses to play various notes

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/OmniMIDI#135]
Thanks for updating it, now there are two more things that are slightly borked.

1. MIDI playback on WMPlayer works just fine now! Black MIDIs do take forever to load, but that's just wmplayer. The problem is when you close out of it. When you close out of wmplayer, it gives a buffer error and then closes.

![buffererrpr](https://user-images.githubusercontent.com/19188146/53175104-530b9280-35b9-11e9-9701-0ed7f82a6af7.PNG)

2. MAMPlayer does play MIDIs now, but some notes refuse to play, mainly long sound effect notes. Upon closing the application, MAMPlayer does not output an error.

Attached are two debug logs.
https://pst.moe/paste/ecdtfb - wmplayer.exe - 21-02-2019 14.12.47 (Debug output).txt
https://pst.moe/paste/djjefm - MAMPlayer.exe - 21-02-2019 14.16.43 (Debug output).txt

-------------------------------------
addtl. info:
Same computer as before, and version of OmniMIDI is 6.3.0, Canary Build 9. Soundfont is FluidR3_GM.sf2.

**Comment by KaleidonKep99** [comment]
MAMPlayer only supports NoteON/OFF events and drums by design.
It has partial support for some events, but most of the time they aren't parsed properly and mess up with the audio.
If the audio in Stream Mode *(MAMPlayer uses the MIDI Stream API)* sounds good in another app, but still sounds weird in MAMPlayer, then it's clearly its fault.
I tested Stream Mode with a few compatible apps *(ZDoom, EDuke32 and TMIDI Player by Fummy)* and they all behave as expected.

About Windows Media Player, I'll look into it now.

**Comment by KaleidonKep99** [comment]
Fixed!
Release: https://github.com/KeppySoftware/OmniMIDI/releases/tag/6.3.0.10
