### ISSUE TITLE
Synthesia doesn't work with OmniMIDI

### ISSUE THREAD

**Issue by sunryze-git** [KaleidonKep99/OmniMIDI#136]
**Problem**
Synthesia does not work well with OmniMIDI and crashes when selecting it.

**Steps to reproduce**
1. Do the Windows Multimedia Wrapper patch on Synthesia
2. Open synthesia
3. Goto settings, select OmniMIDI
4. Click enable

**Expected behavior**
I expected of Synthesia normally working fine with OmniMIDI, but this time does not work.

**Environment**
 - Operating system: Windows 10 1903 Insider (tested on 1809 too)
 - CPU: Intel Core i5 8400
 - RAM: 16GB DDR4
 - MIDI application: Synthesia (All versions)
 - Version of the driver: x.x.x.x

**Additional context**
Used to work in the past.

**Comment by KaleidonKep99** [comment]
![immagine](https://user-images.githubusercontent.com/11065274/53615882-5b2e8800-3be0-11e9-9078-a11ae4257549.png)
Seems to work fine on my end.
I think this might be Synthesia's fault, since it ships with a BASSMIDI-based synth out of the box.
Disable the built-in MIDI synthesizer in Synthesia, restart it then enable OmniMIDI.

I already reported this issue to Nicholas, but he doesn't seem to want to fix it.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
