### ISSUE TITLE
Keppy's Driver crashes Squeak (or Scratch 1.4)

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#14]
Using Squeak (or Scratch 1.4) to open a MIDI port, the VM itself crashes.
[Example](http://youtu.be/z20PKlQww8M)

**Comment by KaleidonKep99** [comment]
Looks like a stack overflow, but I don't know what part of Keppy's Driver is causing it, since Scratch refuses to give me a valid dump file.

I guess it's because of how old Scratch is.

I'll just add Scratch to the blacklist, I really don't want to write Keppy's Driver from scratch (heh) just for an old program with really bad Virtual Machine emulation.

**Comment by DevanWolf** [comment]
The VM crash for Scratch still happens with Keppy's Synthesizer, but you accidentally removed Scratch from the perma-ban black list!
