### ISSUE TITLE
ASIO Support?

### ISSUE THREAD

**Issue by ghost** [KaleidonKep99/OmniMIDI#40]

**Comment by KaleidonKep99** [comment]
_Most likely not_, but I'm looking further into it.

XAudio is already a good engine to achieve really low latencies (Since it directly interfaces with WASAPI on Vista and newer), but I've also been interested a lot into ASIO support.
Issue is, I'd have to integrate support for ASIO devices into the driver and the configurator, which will be pretty hard (The configurator will have to detect the available devices, and put them in a list, then the driver also has to support ASIO devices, but that's easy since BASSASIO is available).

I can't promise anything, but I'll see what I can do about it.
