### ISSUE TITLE
Error when starting playback with DLL override

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#50]
![untitled](https://cloud.githubusercontent.com/assets/15729831/22615622/0e3455d8-eacb-11e6-918c-38195d229160.png)
Somehow after upgrading to 4.0.6.9, DLL override causes an error when starting playback (it can still play normally however). If I remove my DLLs then the error is gone.

**Comment by KaleidonKep99** [comment]
![image](https://cloud.githubusercontent.com/assets/11065274/22618989/c4b05784-eaea-11e6-8c07-e6a39b4487a4.png)

It should throw the right error now.
It happens when you use old libraries, since Keppy's Synthesizer includes functions that aren't supported by old BASSMIDI libraries.

I'll push the driver with the fixed dialog with verssion 4.0.6.10.
